# Install via
# $ brew tap Homebrew/bundle
# $ brew bundle

# This puts the applications in the correct folder
cask_args appdir: '/Applications'

# List of brew repositories
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'caskroom/versions'
tap 'homebrew/versions'
tap 'jbwhit/tap'

cask 'sublime-text'
