# Install via
# $ brew tap Homebrew/bundle
# $ brew bundle

cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'caskroom/versions'
tap 'homebrew/versions'

# This installs helper functions.
tap 'jbwhit/tap'
brew 'nb3automation'

# To print pdfs that have fonts that the
# printer doesn't understand print from adobe reader
cask 'adobe-reader'
# Video app
cask 'vlc'
# Music app
cask 'spotify'
# Slack
cask 'slack'
