# Install via
# $ brew tap Homebrew/bundle
# $ brew bundle

cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'caskroom/versions'
tap 'homebrew/versions'

# This installs helper functions.
tap 'jbwhit/tap'
brew 'nb3automation'

cask 'adobe-reader'
cask 'vlc'
cask 'spotify'
cask 'slack'
